### ISSUE TITLE
Unable to change Home Fragment Divider color

### ISSUE THREAD

**Issue by penkesiva** [penkesiva/testprep#1]
The idea is to use minimal colors in the whole of app design. The Equality Empowerment logo has Indian flag colors and hence the app theme colors.

TODO: Change divider color to black

**Comment by salgubelli** [comment]
Reason: it is an image. Get rid of background in style definition or just set to the default color.

**Comment by penkesiva** [comment]
Thanks @salgubelli. I created an asset called flag-divider to set as a divider drawable.
