### ISSUE TITLE
Create a login page

### ISSUE THREAD

**Issue by penkesiva** [penkesiva/testprep#2]
The login page shall contain the basic information like below -
First Name
Last Name
Email Address (UserName)

**Comment by salgubelli** [comment]
Created register screen to display when app opened for the first time. User is allowed to enter the app only after registring as new user or signed in with existing credentials. Screen contains 'Display Name' and 'Email Address' fields to enter with display name limited to a max of 10 chars. User can create new profile with never used email address, or sign in with an already registered email address. During sign in, user can reuse previously registered display name or choose a new one. A default password ("ugulet") is used to register the user with Firebase. Display name is displayed on navigation bar and settings screen. Email is displayed in settings screen.

Do we need to provide unregister/signout option? instead user can uninstall the app.
