### ISSUE TITLE
Stacking Fragments

### ISSUE THREAD

**Issue by penkesiva** [penkesiva/testprep#30]
When in Practice Question Fragment

Back button shall bring back the previous top fragment (ex: practice or year or subject)
next button shall bring back the next question fragment
previous button shall bring back the previous question fragment

**Comment by salgubelli** [comment]
Let's reframe the problem to a different context ...

do any two of steps 1-3 

Step-1) Side menu -> practice -> select a practice category -> shows first question

Step-2) Side menu -> quiz -> select a quiz -> shows first question

Step-3) Side menu -> model test -> select a model test -> shows first question

keep [ressing back key

Result: exits test/practice -> tetst category screen -> home screen => then goes to previous category

**Comment by penkesiva** [comment]
Can we close this now?

**Comment by salgubelli** [comment]
It is still reproducible ... 
practice -> select a practice test -> start ----> without pressing back -> select quiz from toolbar -> select a quiz -> start -> back + exit + back + back => should show overlapping fragments
