### ISSUE TITLE
Welcome *username*

### ISSUE THREAD

**Issue by penkesiva** [penkesiva/testprep#5]
The home page should welcome user with his/her name. Example: Welcome, Ravi. Good Morning!

**Comment by penkesiva** [comment]
Welcome username on nav drawer and signout in Settings

**Comment by salgubelli** [comment]
Sign out in settings required? what is the behavior on clicking sign out? sign out and re-launch the app

**Comment by penkesiva** [comment]
I think signout is required for balancing it out with signin. We would show the sign-in screen and hide all the app's content. On clicking the sign-out in settings, the UI will return to sign-in UI (no need to relaunch the app).

We can also use this activity to close the database so that any pending writes will happen; also to push final statistics to the cloud. A 'remember me' option will help user for ease of login next time.
